name: Daily Card Event Automation

on:
  schedule:
    # 每天下午3點執行 (UTC+8 15:00 = UTC 07:00)
    - cron: '0 7 * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Create .env file
      run: |
        echo "API_KEY_2CAPTCHA=${{ secrets.API_KEY_2CAPTCHA }}" >> .env
        echo "SID=${{ secrets.SID }}" >> .env
        echo "BIRTH=${{ secrets.BIRTH }}" >> .env
        echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> .env
        echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        
    - name: Run automation
      run: |
        python main.py --headless
        
    - name: Upload logs (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: automation-logs
        path: logs/
        retention-days: 7
